repos:
  # 1 Vimscript Linter (vint)
  - repo: local
    hooks:
      - id: vint
        name: Vim Linter (Vint)
        entry: bash -c 'vint --style-problem --color "$@" || (echo "❌ Fix errors and re-commit!"; exit 1)' --
        language: system  # Fix: `python` was incorrect, should be `system`
        files: '(.*vimrc|.*\.vim)$'
        exclude: ".*\\.plug.vim"

  # 2 Lua Formatter (stylua)
  - repo: local
    hooks:
      - id: stylua
        name: Lua Formatter (Stylua)
        entry: stylua
        language: system
        types: [lua]

  # 3 JSON Formatter (fixjson)
  - repo: local
    hooks:
      - id: fixjson
        name: JSON Formatter
        entry: npx fixjson
        language: system
        types: [json]

  # 4 Python Code Sorter (isort)
  - repo: https://github.com/pycqa/isort
    rev: "6.0.0"  # Use the latest stable version
    hooks:
      - id: isort
        args: ["--profile", "black"]

  # 5 Python Formatter (black)
  - repo: https://github.com/psf/black
    rev: 25.1.0  # Use the latest version (check GitHub)
    hooks:
      - id: black
        args: ["--quiet", "--line-length", "80"]
